AppLink.Payroll/Controllers/HomeController.cs
using AppLink.Payroll.Domain.Entities;
using AppLink.Payroll.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
namespace AppLink.Payroll.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            var employees = db.Employees.Include(e => e.User);
            return View(employees.ToList());
          
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AppLink.Payroll/Controllers/SalaryController.cs
using AppLink.Payroll.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppLink.Payroll.Controllers
{
    public class SalaryController : Controller
    {
        // GET: Salary
     public ActionResult ComputeSalary(int id)
        {



            return View();
        }
        [HttpPost]
        public ActionResult ComputeSalary(int id, ComputeSalaryViewModel model)
        {

            
            return View();
        }

    }


}

AppLink.Payroll/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AppLink.Payroll/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AppLink.Payroll/Views/Home/Index.cshtml
@model IEnumerable<AppLink.Payroll.Domain.Entities.Employee>
@{
    ViewBag.Title = "Home Page";
}

    <h2>Compute Salary</h2>

<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MiddleName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>
                @Html.DisplayFor(i => item.EmployeeNumber)
            </th>
            <th>
                @Html.DisplayFor(i => item.LastName)
            </th>
            <th>
                @Html.DisplayFor(i => item.FirstName)
            </th>
            <th>
                @Html.DisplayFor(i => item.MiddleName)
            </th>
            <th>
                @Html.ActionLink("Compute Salary","ComputeSalary","Salary",new { id=item.Id},null)
            </th>
        </tr>
    }
</table>